### ISSUE TITLE
[Feature] ClanRank

### ISSUE THREAD

**Issue by IgNit3R** [zzbslayer/KokkoroBot-Multi-Platform#1]
Hoshino的话，可以缝合Yobot，整体迁移的话应该问题不大？
如果可以的话能缝一个clanrnak吗

**Comment by zzbslayer** [comment]
在做了在做了…… 目前还在一点一点迁移当中。
请问 clanrnak是什么功能？

**Comment by zzbslayer** [comment]
对于 HoshinoBot 本体的移植，目前主要 Block 在 Scheduler 与 HoshinoBot 的 clanBattle功能
1. 由于 Hoshino 使用 Nonebot 的 Scheduler，对于微博推送、定时提醒相关功能暂时无法移植，得考虑一下怎么保证原有接口实现 Scheduler。
2. 而会战功能 v3 目前未完成，所以只考虑移植会战v2。得把会战功能中 Nonebot `on_message` 接口迁移至 Service 的 `on_prefix` 接口中。难度较小，工程量较大。

**Comment by zzbslayer** [comment]
至于 yobot，我暂时没有看过那边代码。但是我猜测 yobot 既然能缝合到 HoshinoBot 本体，那么 yobot 的代码估计也是大量耦合 `CQEvent`、`on_message`等 Nonebot 概念。 以 `on_message` 为例，首先得将 yobot 当中所有 `on_message` 迁移至 Hoshino v2 接口中的 `on_prefix` 或其他装饰器。 保证 yobot 业务逻辑与 Nonebot、CQHttp 解耦合。

因此 yobot 的缝合甚至是一个更大的工程，·甚至可以单独再开一个项目。至少在 HoshinoBot 本体完全移植完毕前，我暂时不打算做。
如果另外有人愿意同步进行移植那当然时最好的。这样不光可以在 QQ、discord 平台使用，还可以随时切换到其他 IM 平台。

**Comment by zzbslayer** [comment]
大概看了一下 yobot 那边的情况。
如同作者所言，yobot 与 cqhttp 严重耦合。它之所以能够简单的缝合至 HoshinobBot 是因为 HoshinoBot 使用 NoneBot，NoneBot 使用 cqhttp。完美作为 NoneBot 插件运行。
https://github.com/pcrbot/yobot/tree/master/src/client
本项目的目的是与 NoneBot 这些东西解耦合…… 缝合 yobot 必须将 yobot 按照本项目的设计理念进行全面改动。

~~只能指望有大佬愿意开坑将 yobot 整个重构一遍~~

**Comment by IgNit3R** [comment]
clanrank是查询工会战排名的
[github.com/Kengxxiao/Kyouka](url)

**Comment by zzbslayer** [comment]
这个之前我自己的分支版本就有这个功能，但似乎他的 api 或者接口偶尔会变，用了一段时间就失效了…
这个估计到时候跟会战功能一起做，会战功能本身更重要一点。~~现在还没到会战 先摸鱼~~

**Comment by zzbslayer** [comment]
忘记改这个issue了。国服直接用bigfun工具查排名吧……
bot真要弄不如返回一个bigfun的链接……
